import type { GeneratedSet } from './types';

export const mockSets: GeneratedSet[] = [
  {
    title: 'Biology: Human Organs',
    description: 'AI-generated study set covering the major organs of the human body.',
    subject: 'Biology',
    summary: [
      'This set covers 10 major organs of the human body and their functions.',
      'Topics include: Heart, Lungs, Brain, Liver, Kidneys, and more.',
      'Use flashcards mode for active recall, then test yourself with the quiz.',
    ],
    cards: [
      { front: 'Heart', back: 'A muscular organ that pumps blood throughout the body via the circulatory system. Has four chambers: left/right atria and left/right ventricles.' },
      { front: 'Lungs', back: 'Paired organs responsible for gas exchange — taking in oxygen and releasing carbon dioxide. Contains millions of alveoli for surface area.' },
      { front: 'Brain', back: 'The central organ of the nervous system. Controls thoughts, memory, movement, and vital functions. Divided into cerebrum, cerebellum, and brainstem.' },
      { front: 'Liver', back: "The largest internal organ. Performs over 500 functions including detoxification, protein synthesis, and bile production." },
      { front: 'Kidneys', back: 'Paired organs that filter blood to produce urine, regulate blood pressure, and maintain electrolyte balance. Each contains ~1 million nephrons.' },
      { front: 'Skin', back: "The body's largest organ. Provides protection, regulates temperature, and contains sensory receptors. Has three layers: epidermis, dermis, hypodermis." },
      { front: 'Stomach', back: 'A muscular organ that digests food using acid and enzymes. Can hold about 1 liter of food and expands when eating.' },
      { front: 'Spleen', back: 'Part of the lymphatic system. Filters blood, recycles old red blood cells, and supports immune function.' },
    ],
  },
  {
    title: 'French Vocabulary — Daily Life',
    description: 'AI-generated study set covering common French vocabulary for daily life.',
    subject: 'French',
    summary: [
      'This set covers 12 essential French vocabulary words for school and daily life.',
      'Topics include: La nourriture, L\'école, Les devoirs, Le professeur, and more.',
      'Practice with flashcards, then quiz yourself for retention.',
    ],
    cards: [
      { front: 'La nourriture', back: "Food. Refers to what is eaten for meals. Example: 'J'aime la nourriture française' (I love French food)." },
      { front: "L'école", back: "School. The place where students go to learn. Example: 'Je vais à l'école à huit heures' (I go to school at eight o'clock)." },
      { front: 'Les devoirs', back: "Homework/Assignments. Tasks assigned by teachers to be completed at home. Example: 'Je fais mes devoirs le soir' (I do my homework in the evening)." },
      { front: 'Le professeur', back: "Teacher/Professor. The person who teaches at a school or university. Example: 'Mon professeur est très patient' (My teacher is very patient)." },
      { front: "L'étudiant / L'étudiante", back: "Student (masculine/feminine). A person who studies at a school. Example: 'Elle est étudiante en médecine' (She is a medical student)." },
      { front: 'La bibliothèque', back: "Library. A place where books are kept for reading and borrowing. Example: 'J'étudie à la bibliothèque' (I study at the library)." },
      { front: "L'examen", back: "Exam/Test. A formal assessment of a student's knowledge. Example: 'J'ai un examen demain' (I have an exam tomorrow)." },
      { front: 'Le cahier', back: "Notebook. A bound book used for writing notes. Example: 'J'écris dans mon cahier' (I write in my notebook)." },
    ],
  },
  {
    title: 'Chemistry: Periodic Table Basics',
    description: 'AI-generated study set covering the periodic table fundamentals.',
    subject: 'Chemistry',
    summary: [
      'This set covers 10 fundamental concepts about the periodic table.',
      'Topics include: Atomic number, Periods, Groups, Metals, Nonmetals, and more.',
      'Master the periodic table with flashcards and quiz modes.',
    ],
    cards: [
      { front: 'Atomic Number', back: 'The number of protons in an atom\'s nucleus. It defines the identity of an element. Elements on the periodic table are arranged by atomic number.' },
      { front: 'Atomic Mass', back: 'The weighted average mass of an element\'s isotopes, measured in atomic mass units (amu). Found below the element symbol on the periodic table.' },
      { front: 'Periods', back: 'The horizontal rows on the periodic table (1-7). Elements in the same period have the same number of electron shells.' },
      { front: 'Groups', back: 'The vertical columns on the periodic table (1-18). Elements in the same group have similar chemical properties and the same number of valence electrons.' },
      { front: 'Metals', back: 'Elements on the left side of the periodic table. They are typically shiny, conductive, malleable, and tend to lose electrons in reactions.' },
      { front: 'Nonmetals', back: 'Elements on the right side of the periodic table. They are typically dull, poor conductors, and tend to gain electrons in reactions.' },
      { front: 'Metalloids', back: 'Elements along the staircase line (B, Si, Ge, As, Sb, Te). They have properties intermediate between metals and nonmetals.' },
      { front: 'Noble Gases', back: 'Group 18 elements (He, Ne, Ar, Kr, Xe, Rn). They have full valence shells, making them extremely unreactive.' },
    ],
  },
  {
    title: 'World History: The Renaissance',
    description: 'AI-generated study set covering the Renaissance period.',
    subject: 'History',
    summary: [
      'This set covers 10 key concepts from the Renaissance period.',
      'Topics include: Humanism, City-states, Patronage, Art, and more.',
      'Explore the rebirth of classical learning and its impact.',
    ],
    cards: [
      { front: 'Renaissance', back: 'A period of cultural rebirth in Europe (~14th-17th century) marked by renewed interest in classical art, literature, and learning. Began in Italy.' },
      { front: 'Humanism', back: 'An intellectual movement focusing on human potential, achievement, and the study of classical texts. Emphasized individualism and secular thinking.' },
      { front: 'Leonardo da Vinci', back: 'The ultimate Renaissance man — painter, inventor, scientist, and engineer. Known for the Mona Lisa and The Last Supper.' },
      { front: 'Michelangelo', back: 'Renowned sculptor and painter. Created the statue of David and painted the Sistine Chapel ceiling.' },
      { front: 'The Printing Press', back: 'Invented by Johannes Gutenberg around 1440. Revolutionized the spread of knowledge by making books affordable and widely available.' },
      { front: 'Florence', back: 'The birthplace of the Renaissance. A wealthy Italian city-state ruled by the Medici family, who were great patrons of the arts.' },
      { front: 'Patronage', back: 'The financial support of artists and scholars by wealthy individuals or institutions. The Medici family were famous patrons.' },
      { front: 'Perspective', back: 'A technique developed during the Renaissance that creates the illusion of 3D depth on a 2D surface. Revolutionized painting.' },
    ],
  },
  {
    title: 'Math: Algebra Fundamentals',
    description: 'AI-generated study set covering algebra fundamentals.',
    subject: 'Math',
    summary: [
      'This set covers 10 core algebra concepts.',
      'Topics include: Variables, Equations, Functions, Slope, and more.',
      'Build your algebra foundation with flashcards and quizzes.',
    ],
    cards: [
      { front: 'Variable', back: 'A symbol (usually a letter like x or y) that represents an unknown or changing number in an equation or expression.' },
      { front: 'Equation', back: 'A mathematical statement that two expressions are equal, shown with the = sign. Example: 2x + 3 = 7.' },
      { front: 'Function', back: 'A relationship where each input has exactly one output. Written as f(x) = expression. Example: f(x) = 2x + 1.' },
      { front: 'Slope', back: 'The steepness of a line, calculated as rise over run (change in y / change in x). Formula: m = (y2 - y1) / (x2 - x1).' },
      { front: 'Y-intercept', back: 'The point where a line crosses the y-axis. In y = mx + b, b is the y-intercept.' },
      { front: 'Coefficient', back: 'The numerical multiplier of a variable. In 3x, the coefficient is 3.' },
      { front: 'Distributive Property', back: 'a(b + c) = ab + ac. Multiplication distributed across addition inside parentheses.' },
      { front: 'Quadratic Equation', back: 'A polynomial equation of degree 2, in the form ax² + bx + c = 0. Solved using the quadratic formula.' },
    ],
  },
  {
    title: 'Physics: Forces and Motion',
    description: 'AI-generated study set covering forces and motion.',
    subject: 'Physics',
    summary: [
      'This set covers 10 key concepts about forces and motion.',
      'Topics include: Newton\'s Laws, Velocity, Acceleration, Friction, and more.',
      'Master the physics of motion with flashcards and quizzes.',
    ],
    cards: [
      { front: "Newton's First Law (Inertia)", back: 'An object at rest stays at rest, and an object in motion stays in motion at constant velocity, unless acted upon by an external force.' },
      { front: "Newton's Second Law", back: 'Force = mass × acceleration (F = ma). The acceleration of an object is directly proportional to the net force and inversely proportional to its mass.' },
      { front: "Newton's Third Law", back: 'For every action, there is an equal and opposite reaction. Forces always come in pairs.' },
      { front: 'Velocity', back: 'Speed in a given direction. A vector quantity. Example: 60 mph north. Speed alone is just magnitude.' },
      { front: 'Acceleration', back: 'The rate of change of velocity over time. Measured in m/s². Can be positive (speeding up) or negative (slowing down).' },
      { front: 'Friction', back: 'A force that opposes motion between two surfaces in contact. Can be static (preventing motion) or kinetic (opposing moving objects).' },
      { front: 'Gravity', back: 'A force that attracts objects with mass toward each other. On Earth, acceleration due to gravity is ~9.8 m/s².' },
      { front: 'Momentum', back: 'The product of mass and velocity (p = mv). A vector quantity. Conserved in a closed system.' },
    ],
  },
  {
    title: 'Spanish Vocabulary — Food & Dining',
    description: 'AI-generated study set covering Spanish food vocabulary.',
    subject: 'Spanish',
    summary: [
      'This set covers 10 essential Spanish food and dining vocabulary words.',
      'Topics include: La comida, El agua, El pan, and more.',
      'Practice with flashcards and quiz yourself for retention.',
    ],
    cards: [
      { front: 'La comida', back: 'Food / Meal. Refers to food in general or the main meal of the day. Example: "La comida está deliciosa" (The food is delicious).' },
      { front: 'El agua', back: 'Water. Note: uses "el" despite being feminine because it starts with a stressed "a". Example: "Necesito agua" (I need water).' },
      { front: 'El pan', back: 'Bread. A staple food in Spanish-speaking countries. Example: "Quiero pan fresco" (I want fresh bread).' },
      { front: 'La fruta', back: 'Fruit. Example: "Me gusta la fruta en el desayuno" (I like fruit for breakfast).' },
      { front: 'El restaurante', back: 'Restaurant. Example: "Vamos al restaurante" (Let\'s go to the restaurant).' },
      { front: 'El desayuno', back: 'Breakfast. The first meal of the day. Example: "Como cereal para el desayuno" (I eat cereal for breakfast).' },
      { front: 'La cena', back: 'Dinner. The main evening meal. Example: "Cenamos a las ocho" (We have dinner at eight).' },
      { front: 'El postre', back: 'Dessert. Sweet course after a meal. Example: "Quiero postre de chocolate" (I want chocolate dessert).' },
    ],
  },
  {
    title: 'Geography: World Continents',
    description: 'AI-generated study set covering the world\'s continents.',
    subject: 'Geography',
    summary: [
      'This set covers 10 key concepts about world continents and geography.',
      'Topics include: All 7 continents, major oceans, and key geographic terms.',
      'Explore our world with flashcards and quiz modes.',
    ],
    cards: [
      { front: 'Africa', back: 'The second-largest continent, home to 54 countries. Features the Sahara Desert, the Nile River (longest in the world), and diverse ecosystems from savanna to rainforest.' },
      { front: 'Asia', back: 'The largest and most populous continent. Contains 48 countries, Mount Everest (highest peak), and the Gobi Desert.' },
      { front: 'Europe', back: 'The second-smallest continent but densely populated. Contains 44 countries. Separated from Asia by the Ural Mountains.' },
      { front: 'North America', back: 'Third-largest continent. Contains 23 countries including the US, Canada, and Mexico. Features the Rocky Mountains and Great Lakes.' },
      { front: 'South America', back: 'Fourth-largest continent. Home to the Amazon Rainforest, the Andes Mountains (longest continental range), and 12 countries.' },
      { front: 'Antarctica', back: 'The southernmost continent, covered almost entirely by ice. No permanent residents — only research stations. Coldest place on Earth.' },
      { front: 'Australia', back: 'The smallest continent and also a country. Known for its unique wildlife (marsupials, monotremes) and the Great Barrier Reef.' },
      { front: 'Pacific Ocean', back: 'The largest and deepest ocean, covering about one-third of Earth\'s surface. Contains the Mariana Trench, the deepest point.' },
    ],
  },
];

export const subjects = [
  'Biology', 'Chemistry', 'Physics', 'Math', 'History', 'French',
  'Spanish', 'English', 'Geography', 'Computer Science', 'General',
];
